# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).




In [ ]:
# No code solution (reading)
# Documentation Reading Notes

# torch.Tensor:
# - Tensors are multi-dimensional arrays (like NumPy), but support GPU acceleration.
# - Common creation functions: torch.tensor(), torch.zeros(), torch.ones(), torch.arange(), torch.rand()
# - Tensor operations: math (+, -, *, @), reshaping (.view(), .reshape()), indexing, slicing
# - Data types: torch.float32, torch.int64, etc.
# - Gradients: Use .requires_grad=True to track operations for automatic differentiation

# torch.cuda:
# - CUDA enables PyTorch to use NVIDIA GPUs for faster computation.
# - Use torch.device('cuda') and .to(device) or .cuda() to move tensors/models to GPU
# - Check availability: torch.cuda.is_available(), torch.cuda.device_count()
# - Manage memory: torch.cuda.empty_cache(), torch.cuda.memory_allocated(), torch.cuda.memory_reserved()

#  Goal: Understand where to find info in the docs and get familiar with key concepts.
# No need to fully understand everything yet — just building awareness.


### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)

print(random_tensor)


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_b = torch.rand(1, 7)

# Perform matrix multiplication
# We need to transpose tensor_b to (7, 1) so it can be multiplied with (7, 7)
result = torch.matmul(random_tensor, tensor_b.T)

print(result)


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
import torch
torch.manual_seed(0)

# Create two random tensors
tensor_a = torch.rand(7, 7)
tensor_b = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.matmul(tensor_a, tensor_b.T)

print(result, result.shape)


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:

# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
import torch
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# Create two random tensors on GPU
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

print(tensor1, tensor2)



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor1 and tensor2
result = torch.matmul(tensor1, tensor2.T)

print(result, result.shape)



### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value = result.max()

# Find min
min_value = result.min()

print("Max:", max_value)
print("Min:", min_value)


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_index = result.argmax()

# Find arg min
min_index = result.argmin()

print("Arg max index:", max_index)
print("Arg min index:", min_index)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
import torch
torch.manual_seed(7)

# Create random tensor
tensor_orig = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_squeezed = tensor_orig.squeeze()

# Print out tensors and their shapes
print(tensor_orig, tensor_orig.shape)
print(tensor_squeezed, tensor_squeezed.shape)
